# -*- coding: utf-8 -*-
"""Collab Setup.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sl4uIe7ytDJlBkfeXq7fma-mcmKSTob9
"""

print("Hello")

"""# New Section

## Welcome to Python
"""

import spacy

print(spacy.__version__)

import nltk

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt